### ISSUE TITLE
Publish in crates.io?

### ISSUE THREAD

**Issue by behnam** [obsoke/rustris#1]
Are you considering to put it on crates.io to be able to install using `cargo install`?

**Comment by obsoke** [comment]
Hello. I'm not sure if games are the sort of thing that belong on crates.io. I always thought crates.io & `cargo` were meant for Rust development dependencies & tools.

There would be other issues such as the fact that this project requires SDL2 to be installed in order to build or run and installing that is outside of the scope of `cargo`. I do want to find a way to properly create cross-platform binaries though. I've tried using [trust](https://github.com/japaric/trust) but have had issue with dependencies & building on Windows.
